# Generated by Django 6.1 on 2026-08-29 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(default='unit', max_length=50)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaborMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role_name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(default='jam', max_length=50)),
                ('standard_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft / Perencanaan'), ('in_progress', 'Sedang Dikerjakan'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20)),
                ('stock_released', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedGoodStockMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mutation_type', models.CharField(choices=[('IN', 'Stock Masuk (In)'), ('OUT', 'Stock Keluar (Out)')], max_length=5)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='hpp.finishedgood')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_mutations', to='hpp.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('item_type', models.CharField(choices=[('assembly', 'Sub-Assembly / Rakitan'), ('material', 'Material / Bahan Mentah')], default='material', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('est_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('est_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('act_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('act_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hpp.bomitem')),
                ('material_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hpp.materialmaster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='hpp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFinishedGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('est_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('est_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('act_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('act_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_usages', to='hpp.finishedgood')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_good_items', to='hpp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role_name', models.CharField(max_length=200)),
                ('unit', models.CharField(default='jam', max_length=50)),
                ('est_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('est_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('act_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('act_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('labor_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hpp.labormaster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_items', to='hpp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('est_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('act_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overhead_items', to='hpp.project')),
            ],
        ),
    ]
