# Generated by Django 6.1 on 2026-08-30 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nik', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(default='Tukang', max_length=100)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('HADIR', 'Hadir / Masuk'), ('IJIN', 'Izin'), ('SAKIT', 'Sakit'), ('ALPHA', 'Alpha / Tanpa Keterangan')], default='HADIR', max_length=10)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('wage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hpp.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
