# Generated by Django 6.1 on 2026-08-30 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpp', '0002_employee_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('activity_category', models.CharField(default='Produksi / Fabrikasi', max_length=100)),
                ('task_description', models.TextField()),
                ('output_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('output_unit', models.CharField(default='unit', max_length=50)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('status', models.CharField(choices=[('completed', 'Selesai'), ('in_progress', 'Sedang Berjalan'), ('pending', 'Tertunda / Terkendala')], default='completed', max_length=20)),
                ('obstacles', models.TextField(blank=True, default='')),
                ('supervisor_rating', models.PositiveSmallIntegerField(choices=[(5, '5 - Sangat Baik'), (4, '4 - Baik'), (3, '3 - Cukup'), (2, '2 - Kurang'), (1, '1 - Sangat Kurang')], default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='hpp.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_work_logs', to='hpp.project')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
