# Generated by Django 6.1 on 2026-08-30 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpp', '0005_customer_project_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, default='Umum', max_length=100)),
                ('stock_unit', models.CharField(default='pcs', max_length=50)),
                ('current_stock', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('last_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('minimum_stock', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='bomitemrealization',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='bomitemrealization',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realizations', to='hpp.rawmaterial'),
        ),
        migrations.CreateModel(
            name='RawMaterialStockMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mutation_type', models.CharField(choices=[('IN', 'Stock Masuk (In)'), ('OUT', 'Stock Keluar (Out)')], max_length=5)),
                ('input_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('input_unit', models.CharField(max_length=50)),
                ('stock_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=15)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_mutations', to='hpp.project')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='hpp.rawmaterial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bomitemrealization',
            name='mutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hpp.rawmaterialstockmutation'),
        ),
        migrations.CreateModel(
            name='RawMaterialUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('unit_name', models.CharField(max_length=50)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='hpp.rawmaterial')),
            ],
            options={
                'ordering': ['unit_name'],
                'unique_together': {('raw_material', 'unit_name')},
            },
        ),
    ]
