# Generated by Django 6.1 on 2026-08-30 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpp', '0006_rawmaterial_alter_bomitemrealization_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('raw_material', 'Bahan Baku'), ('finished_good', 'Barang Jadi'), ('labor', 'Tenaga Kerja'), ('overhead', 'Overhead / Biaya Lain')], db_index=True, default='raw_material', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('code', 'category')},
            },
        ),
    ]
