# Generated by Django 6.1 on 2026-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpp', '0007_unitmaster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishedgood',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='finishedgood',
            name='category',
            field=models.CharField(blank=True, default='Umum', max_length=100),
        ),
        migrations.AddField(
            model_name='finishedgood',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
