# Generated by Django 6.1 on 2026-09-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpp', '0008_alter_finishedgood_options_finishedgood_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
