# Generated by Django 6.1 on 2026-09-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpp', '0009_project_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_items', to='hpp.rawmaterial'),
        ),
    ]
