# Generated by Django 6.1 on 2026-09-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpp', '0010_bomitem_raw_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closing_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
