# Generated by Django 6.1 on 2026-09-08 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpp', '0011_project_closing_notes_project_completed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('LEAVE', 'Cuti (Leave)'), ('SICK', 'Sakit (Sick)'), ('PERMIT', 'Izin (Permit)'), ('OFFICIAL_TRAVEL', 'Dinas Luar / Tugas Lapangan'), ('ABSENT', 'Alpha / Tanpa Keterangan'), ('OTHER', 'Lain-lain')], default='PERMIT', max_length=30)),
                ('is_paid', models.BooleanField(default=False, help_text='Apakah karyawan tetap berhak atas upah harian?')),
                ('wage_percentage', models.DecimalField(decimal_places=2, default=0, help_text='% upah harian yang dibayarkan (100 = penuh, 50 = separuh, 0 = unpaid)', max_digits=5)),
                ('color', models.CharField(choices=[('blue', 'Biru (Izin/Permit)'), ('amber', 'Kuning/Oranye (Sakit)'), ('purple', 'Ungu (Cuti/Leave)'), ('indigo', 'Indigo (Dinas Luar)'), ('rose', 'Merah (Alpha/Mangkir)'), ('slate', 'Abu-abu (Lainnya)')], default='blue', max_length=20)),
                ('requires_attachment', models.BooleanField(default=False, help_text='Wajib melampirkan surat/bukti?')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('HADIR', 'Hadir / Masuk'), ('TIDAK_HADIR', 'Tidak Masuk (Izin/Cuti/Sakit)'), ('IJIN', 'Izin (Legacy)'), ('SAKIT', 'Sakit (Legacy)'), ('ALPHA', 'Alpha (Legacy)')], default='HADIR', max_length=15),
        ),
        migrations.AddField(
            model_name='attendance',
            name='absence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='hpp.absencetype'),
        ),
    ]
