# Generated by Django 6.1 on 2026-09-08 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpp', '0012_absencetype_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworklog',
            name='labor_realization',
            field=models.OneToOneField(blank=True, help_text='Tautan ke baris realisasi tenaga kerja proyek HPP jika sudah dikonversi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_work_log', to='hpp.laborrealization'),
        ),
    ]
